name: Convert README to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install a markdown converter (using pandoc in this example)
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      # Convert README.md to index.html
      - name: Convert README to HTML
        run: |
          pandoc README.md -f markdown -t html -s -o index.html \
          --metadata pagetitle="My Project" \
          --css https://cdn.jsdelivr.net/npm/water.css@2/out/water.css

      # Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
          include_assets: index.html
