name: Publish README to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert README.md to index.html
        run: pandoc README.md -o index.html --metadata title="Project Documentation"

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages

      - name: Remove old index.html (if exists)
        run: rm -f index.html

      - name: Move new index.html to gh-pages branch
        run: mv ../index.html .

      - name: Commit and Push Changes
        run: |
          git add index.html
          git commit -m "Update index.html with latest README" || echo "No changes to commit"
          git push origin gh-pages
