name: Publish README to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert README.md to index.html
        run: pandoc README.md -o index.html --metadata title="Project Documentation"

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          mv index.html .
          git add index.html
          git commit -m "Publish README as GitHub Pages"
          git push -f origin gh-pages
